/*
    Hey this file was generated by Structy on 2021-01-25 19:38:32.012352 from
    gem_monitor_update.structy. Maybe don't edit it!
*/

#include "gem_monitor_update.h"

#define _PACK_STRING "iiHHiiHH?iHHH"

void GemMonitorUpdate_init(struct GemMonitorUpdate* inst) {
    inst->castor_pitch_knob = F16(0);
    inst->castor_pitch_cv = F16(0);
    inst->castor_pulse_width_knob = 0;
    inst->castor_pulse_width_cv = 0;
    inst->pollux_pitch_knob = F16(0);
    inst->pollux_pitch_cv = F16(0);
    inst->pollux_pulse_width_knob = 0;
    inst->pollux_pulse_width_cv = 0;
    inst->button_state = false;
    inst->lfo_intensity = F16(0);
    inst->loop_time = 0;
    inst->animation_time = 0;
    inst->sample_time = 0;
}

struct StructyResult GemMonitorUpdate_pack(const struct GemMonitorUpdate* inst, uint8_t* buf) {
    return structy_pack(
        _PACK_STRING,
        buf,
        GEMMONITORUPDATE_PACKED_SIZE,
        inst->castor_pitch_knob,
        inst->castor_pitch_cv,
        inst->castor_pulse_width_knob,
        inst->castor_pulse_width_cv,
        inst->pollux_pitch_knob,
        inst->pollux_pitch_cv,
        inst->pollux_pulse_width_knob,
        inst->pollux_pulse_width_cv,
        inst->button_state,
        inst->lfo_intensity,
        inst->loop_time,
        inst->animation_time,
        inst->sample_time);
}

struct StructyResult GemMonitorUpdate_unpack(struct GemMonitorUpdate* inst, const uint8_t* buf) {
    return structy_unpack(
        _PACK_STRING,
        buf,
        GEMMONITORUPDATE_PACKED_SIZE,
        &inst->castor_pitch_knob,
        &inst->castor_pitch_cv,
        &inst->castor_pulse_width_knob,
        &inst->castor_pulse_width_cv,
        &inst->pollux_pitch_knob,
        &inst->pollux_pitch_cv,
        &inst->pollux_pulse_width_knob,
        &inst->pollux_pulse_width_cv,
        &inst->button_state,
        &inst->lfo_intensity,
        &inst->loop_time,
        &inst->animation_time,
        &inst->sample_time);
}

void GemMonitorUpdate_print(const struct GemMonitorUpdate* inst) {
    // TODO: Print pointer address.
    STRUCTY_PRINTF("Struct GemMonitorUpdate:\n");
    {
        char fix16buf[13];
        fix16_to_str(inst->castor_pitch_knob, fix16buf, 2);
        STRUCTY_PRINTF("- castor_pitch_knob: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->castor_pitch_cv, fix16buf, 2);
        STRUCTY_PRINTF("- castor_pitch_cv: %s\n", fix16buf);
    }
    STRUCTY_PRINTF("- castor_pulse_width_knob: %u\n", inst->castor_pulse_width_knob);
    STRUCTY_PRINTF("- castor_pulse_width_cv: %u\n", inst->castor_pulse_width_cv);
    {
        char fix16buf[13];
        fix16_to_str(inst->pollux_pitch_knob, fix16buf, 2);
        STRUCTY_PRINTF("- pollux_pitch_knob: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->pollux_pitch_cv, fix16buf, 2);
        STRUCTY_PRINTF("- pollux_pitch_cv: %s\n", fix16buf);
    }
    STRUCTY_PRINTF("- pollux_pulse_width_knob: %u\n", inst->pollux_pulse_width_knob);
    STRUCTY_PRINTF("- pollux_pulse_width_cv: %u\n", inst->pollux_pulse_width_cv);
    STRUCTY_PRINTF("- button_state: %u\n", inst->button_state);
    {
        char fix16buf[13];
        fix16_to_str(inst->lfo_intensity, fix16buf, 2);
        STRUCTY_PRINTF("- lfo_intensity: %s\n", fix16buf);
    }
    STRUCTY_PRINTF("- loop_time: %u\n", inst->loop_time);
    STRUCTY_PRINTF("- animation_time: %u\n", inst->animation_time);
    STRUCTY_PRINTF("- sample_time: %u\n", inst->sample_time);
}
