/*
    Hey this file was generated by Structy on 2021-01-14 04:06:57.566641 from
    gem_settings.structy. Maybe don't edit it!
*/

#include "gem_settings.h"

#define _PACK_STRING "HhHiiiiiiiiiiH??i"

void GemSettings_init(struct GemSettings* inst) {
    inst->adc_gain_corr = 2048;
    inst->adc_offset_corr = 0;
    inst->led_brightness = 127;
    inst->castor_knob_min = F16(-1.01);
    inst->castor_knob_max = F16(1.01);
    inst->pollux_knob_min = F16(-1.01);
    inst->pollux_knob_max = F16(1.01);
    inst->chorus_max_intensity = F16(0.05);
    inst->lfo_frequency = F16(0.2);
    inst->knob_offset_corr = F16(0.0);
    inst->knob_gain_corr = F16(1.0);
    inst->smooth_initial_gain = F16(0.1);
    inst->smooth_sensitivity = F16(30.0);
    inst->pollux_follower_threshold = 56;
    inst->castor_lfo_pwm = false;
    inst->pollux_lfo_pwm = false;
    inst->pitch_knob_nonlinearity = F16(0.6);
}

struct StructyResult GemSettings_pack(const struct GemSettings* inst, uint8_t* buf) {
    return structy_pack(
        _PACK_STRING,
        buf,
        GEMSETTINGS_PACKED_SIZE,
        inst->adc_gain_corr,
        inst->adc_offset_corr,
        inst->led_brightness,
        inst->castor_knob_min,
        inst->castor_knob_max,
        inst->pollux_knob_min,
        inst->pollux_knob_max,
        inst->chorus_max_intensity,
        inst->lfo_frequency,
        inst->knob_offset_corr,
        inst->knob_gain_corr,
        inst->smooth_initial_gain,
        inst->smooth_sensitivity,
        inst->pollux_follower_threshold,
        inst->castor_lfo_pwm,
        inst->pollux_lfo_pwm,
        inst->pitch_knob_nonlinearity
    );
}

struct StructyResult GemSettings_unpack(struct GemSettings* inst, const uint8_t* buf) {
    return structy_unpack(
        _PACK_STRING,
        buf,
        GEMSETTINGS_PACKED_SIZE,
        &inst->adc_gain_corr,
        &inst->adc_offset_corr,
        &inst->led_brightness,
        &inst->castor_knob_min,
        &inst->castor_knob_max,
        &inst->pollux_knob_min,
        &inst->pollux_knob_max,
        &inst->chorus_max_intensity,
        &inst->lfo_frequency,
        &inst->knob_offset_corr,
        &inst->knob_gain_corr,
        &inst->smooth_initial_gain,
        &inst->smooth_sensitivity,
        &inst->pollux_follower_threshold,
        &inst->castor_lfo_pwm,
        &inst->pollux_lfo_pwm,
        &inst->pitch_knob_nonlinearity
    );
}

void GemSettings_print(const struct GemSettings* inst) {
    // TODO: Print pointer address.
    STRUCTY_PRINTF("Struct GemSettings:\n");
    STRUCTY_PRINTF("- adc_gain_corr: %u\n", inst->adc_gain_corr);
    STRUCTY_PRINTF("- adc_offset_corr: %d\n", inst->adc_offset_corr);
    STRUCTY_PRINTF("- led_brightness: %u\n", inst->led_brightness);
    {
        char fix16buf[13];
        fix16_to_str(inst->castor_knob_min, fix16buf, 2);
        STRUCTY_PRINTF("- castor_knob_min: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->castor_knob_max, fix16buf, 2);
        STRUCTY_PRINTF("- castor_knob_max: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->pollux_knob_min, fix16buf, 2);
        STRUCTY_PRINTF("- pollux_knob_min: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->pollux_knob_max, fix16buf, 2);
        STRUCTY_PRINTF("- pollux_knob_max: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->chorus_max_intensity, fix16buf, 2);
        STRUCTY_PRINTF("- chorus_max_intensity: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->lfo_frequency, fix16buf, 2);
        STRUCTY_PRINTF("- lfo_frequency: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->knob_offset_corr, fix16buf, 2);
        STRUCTY_PRINTF("- knob_offset_corr: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->knob_gain_corr, fix16buf, 2);
        STRUCTY_PRINTF("- knob_gain_corr: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->smooth_initial_gain, fix16buf, 2);
        STRUCTY_PRINTF("- smooth_initial_gain: %s\n", fix16buf);
    }
    {
        char fix16buf[13];
        fix16_to_str(inst->smooth_sensitivity, fix16buf, 2);
        STRUCTY_PRINTF("- smooth_sensitivity: %s\n", fix16buf);
    }
    STRUCTY_PRINTF("- pollux_follower_threshold: %u\n", inst->pollux_follower_threshold);
    STRUCTY_PRINTF("- castor_lfo_pwm: %u\n", inst->castor_lfo_pwm);
    STRUCTY_PRINTF("- pollux_lfo_pwm: %u\n", inst->pollux_lfo_pwm);
    {
        char fix16buf[13];
        fix16_to_str(inst->pitch_knob_nonlinearity, fix16buf, 2);
        STRUCTY_PRINTF("- pitch_knob_nonlinearity: %s\n", fix16buf);
    }
}
