#pragma once

/*
    Hey this file was generated by Structy on 2021-01-25 19:38:32.012352 from
    gem_monitor_update.structy. Maybe don't edit it!
*/

#include "structy.h"

#include "fix16.h"

#define GEMMONITORUPDATE_PACKED_SIZE 35

struct GemMonitorUpdate {
    fix16_t castor_pitch_knob;
    fix16_t castor_pitch_cv;
    uint16_t castor_pulse_width_knob;
    uint16_t castor_pulse_width_cv;
    fix16_t pollux_pitch_knob;
    fix16_t pollux_pitch_cv;
    uint16_t pollux_pulse_width_knob;
    uint16_t pollux_pulse_width_cv;
    bool button_state;
    fix16_t lfo_intensity;
    uint16_t loop_time;
    uint16_t animation_time;
    uint16_t sample_time;
};

void GemMonitorUpdate_init(struct GemMonitorUpdate* inst);
struct StructyResult GemMonitorUpdate_pack(const struct GemMonitorUpdate* inst, uint8_t* buf);
struct StructyResult GemMonitorUpdate_unpack(struct GemMonitorUpdate* inst, const uint8_t* buf);
void GemMonitorUpdate_print(const struct GemMonitorUpdate* inst);
