# Hey this file was generated by Structy on 2021-01-14 03:03:03.092407 from
# gem_settings.structy. Maybe don't edit it!

from dataclasses import dataclass
from typing import ClassVar

import structy


@dataclass
class GemSettings(structy.Struct):
    _PACK_STRING: ClassVar[str] = "HhHiiiiiiiiiiH??i"

    PACKED_SIZE: ClassVar[int] = 54
    """The total size of the struct once packed."""

    adc_gain_corr: int = 2048
    """The ADC's internal gain correction register."""

    adc_offset_corr: int = 0
    """The ADC's internal offset correction register."""

    led_brightness: int = 127
    """The front-plate LED brightness."""

    castor_knob_min: structy.Fix16 = -1.01
    """Configuration for the CV knob mins and maxs in volts, defaults to -1.01 to +1.01."""

    castor_knob_max: structy.Fix16 = 1.01

    pollux_knob_min: structy.Fix16 = -1.01

    pollux_knob_max: structy.Fix16 = 1.01

    chorus_max_intensity: structy.Fix16 = 0.05
    """Maximum amount that the chorus can impact Pollux's frequency."""

    chorus_max_frequency: structy.Fix16 = 0.2
    """Maximum frequency that the chorus can run at in hertz."""

    knob_offset_corr: structy.Fix16 = 0.0
    """Error correction for the ADC readings for the CV and PWM knobs."""

    knob_gain_corr: structy.Fix16 = 1.0

    smooth_initial_gain: structy.Fix16 = 0.1
    """Pitch input CV smoothing parameters."""

    smooth_sensitivity: structy.Fix16 = 30.0

    pollux_follower_threshold: int = 56
    """This is the "deadzone" for Pollux's pitch CV input, basically, it
           should be around 0v and it's the point where Pollux starts following
           Castor's pitch CV. By default this is 6 code points to allow some
           variance in time and temperature."""

    castor_lfo_pwm: bool = False
    """Route LFO to PWM for oscillators"""

    pollux_lfo_pwm: bool = False

    pitch_knob_nonlinearity: structy.Fix16 = 0.33
    """The firmware adjusts the pitch CV knobs so that it's easier to tune
           the oscillators. It does this by spreading the values near the center
           of the knob out so that the range at the center is more fine. This
           makes the knobs non-linear. This setting controls how "intense"
           this non-linearity is. A value of 0.33 is equivalent to a linear
           response. Higher values make it easier and easier to tune the
           oscillator but sacrifice the range, values lower than 0.33 will
           make it harder to tune and aren't recommended."""
