# Hey this file was generated by Structy on 2021-01-25 19:38:32.369387 from
# gem_monitor_update.structy. Maybe don't edit it!

from dataclasses import dataclass
from typing import ClassVar

import structy


@dataclass
class GemMonitorUpdate(structy.Struct):
    _PACK_STRING: ClassVar[str] = "iiHHiiHH?iHHH"

    PACKED_SIZE: ClassVar[int] = 35
    """The total size of the struct once packed."""

    castor_pitch_knob: structy.Fix16 = 0

    castor_pitch_cv: structy.Fix16 = 0

    castor_pulse_width_knob: int = 0

    castor_pulse_width_cv: int = 0

    pollux_pitch_knob: structy.Fix16 = 0

    pollux_pitch_cv: structy.Fix16 = 0

    pollux_pulse_width_knob: int = 0

    pollux_pulse_width_cv: int = 0

    button_state: bool = False

    lfo_intensity: structy.Fix16 = 0

    loop_time: int = 0

    animation_time: int = 0

    sample_time: int = 0
