# Hey this file was generated by Structy from
# gem_monitor_update.structy. Maybe don't edit it!

from dataclasses import dataclass
from typing import ClassVar

import structy


@dataclass
class GemMonitorUpdate(structy.Struct):
    _PACK_STRING : ClassVar[str] = "B?HHHHHHHHBiHIHHHHHHHiBiHIHHHH"

    PACKED_SIZE : ClassVar[int] = 66
    """The total size of the struct once packed."""

    mode: int = 0

    tweaking: bool = False

    lfo_knob: int = 0

    tweak_lfo_knob: int = 0

    castor_pitch_knob: int = 0

    castor_pitch_cv: int = 0

    castor_pulse_knob: int = 0

    castor_pulse_cv: int = 0

    castor_tweak_pitch_knob: int = 0

    castor_tweak_pulse_knob: int = 0

    castor_pitch_behavior: int = 0

    castor_pitch: structy.Fix16 = 0

    castor_pulse_width: int = 0

    castor_period: int = 0

    castor_ramp: int = 0

    pollux_pitch_knob: int = 0

    pollux_pitch_cv: int = 0

    pollux_pulse_knob: int = 0

    pollux_pulse_cv: int = 0

    pollux_tweak_pitch_knob: int = 0

    pollux_tweak_pulse_knob: int = 0

    pollux_reference_pitch: structy.Fix16 = 0

    pollux_pitch_behavior: int = 0

    pollux_pitch: structy.Fix16 = 0

    pollux_pulse_width: int = 0

    pollux_period: int = 0

    pollux_ramp: int = 0

    loop_time: int = 0

    animation_time: int = 0

    sample_time: int = 0
